### ISSUE TITLE
Font stylesheet is missing parts in copied version

### ISSUE THREAD

**Issue by benni3005** [maikschneider/bw_icons#59]
Hi there,

we have a local stylesheet from Icomoon, whcih looks like this:

```css
@font-face {
  font-family: "icomoon";
  src: url("fonts/icomoon.eot?sfzcx2");
  src:
    url("fonts/icomoon.eot?sfzcx2#iefix") format("embedded-opentype"),
    url("fonts/icomoon.woff2?sfzcx2") format("woff2"),
    url("fonts/icomoon.ttf?sfzcx2") format("truetype"),
    url("fonts/icomoon.woff?sfzcx2") format("woff"),
    url("fonts/icomoon.svg?sfzcx2#icomoon") format("svg");
  font-weight: normal;
  font-style: normal;
  font-display: block;
}

[class^="icon-"],
[class*=" icon-"] {
  /* use !important to prevent issues with browser extensions that change fonts */
  font-family: "icomoon" !important;
  speak: never;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;

  /* Better Font Rendering =========== */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.icon-foobar:before {
  content: "\e900";
}
```

But after the file gets copied over to `/public/typo3temp/tx_bwicons/[...]` it looks like this:

```css
@font-face {
  font-family: "icomoon";
  src: url("icomoon.eot?sfzcx2");
  src:
    url("icomoon.eot?sfzcx2#iefix") format("embedded-opentype"),
    url("icomoon.woff2?sfzcx2") format("woff2"),
    url("icomoon.ttf?sfzcx2") format("truetype"),
    url("icomoon.woff?sfzcx2") format("woff"),
    url("icomoon.svg?sfzcx2#icomoon") format("svg");
  font-weight: normal;
  font-style: normal;
  font-display: block;
}

.icon-foobar:before {
  content: "\e900";
}
```

So basically the selector `[class^="icon-"], [class*=" icon-"]` with all its contents is missing and therefore the icons don't get rendered correctly in the Typo3 backend showing only squares, since the font never was requested by the browser.

Greetings,
Benni
